apiVersion: v1
kind: Service
metadata:
  name: progress-db
  labels:
    app: progress-db
    service: progress
spec:
  selector:
    app: progress-db
    service: progress
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP