apiVersion: v1
kind: Service
metadata:
  name: progress
  labels:
    app: progress
    service: progress
spec:
  selector:
    app: progress
    service: progress
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP